version: "3.4"

#APARTIR DESSE PONTO INICIAMOS A CRIAÇÃO DOS SERVIÇOS NECESSARIOS PARA O LAB


services:
        nginx:
                image: nginx:latest
                container_name: proxy_reverso
                network:
                        vlan_20:
                                ipv4_address: 192.168.2.2/24

                ports:
                        - 80:80

        web_server_01:
                image: httpd:latest
                container_name: web_server_01
                volumes:
                        - ./web01/:/usr/local/apache2/htdocs/
                ports:
                        - 81:80


        web_server_02:
                image: httpd:latest
                container_name: web_server_02
                volumes:
                        - ./web02/:/usr/local/apache2/htdocs/
                ports:
                        - 82:80


        zabbix:
                image: zabbix/zabbix-appliance
                container_name: zabbix
                ports:
                        - 83:80


networks:

        vlan_10:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.1.0/24
                                
                
                 
        vlan_20:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.2.0/24
                                 
                               
        vlan_30:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 10.1.1.0/24
                           


